server:
  port: 8080

spring:
  application:
    name: apollo

app:
  id: test

apollo:
  meta: http://127.0.0.1:8080
  cluster: default
  bootstrap:
    enabled: true
    namespaces: test,application
