language: java

jdk:
    - openjdk8

install: true

cache:
  directories:
    - "$HOME/.m2"

script:
  - travis_wait 120 ./mvnw -B --no-transfer-progress clean install cobertura:cobertura -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"