# 配置启动端口
server:
  port: 7001
# Spring应用（微服务）名称
spring:
  application:
    name: gateway-fund
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    consul:
#      host: 127.0.0.1
#      port: 8500