version: 2.1

orbs:
  maven: circleci/maven@0.0.12

commands:
  with_cache:
    parameters:
      steps:
        type: steps
    steps:
      - run: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - steps: << parameters.steps >>
      - save_cache:
          paths:
            - ~/.m2/repository
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}


workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
