server:
  port: 8888

spring:
  application:
    name: apollo

app:
  id: 1001

apollo:
  cluster: default
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://192.168.88.113:8080
