# 配置启动端口
server:
  port: 3001
# Spring应用（微服务）名称
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    consul:
#      host: 127.0.0.1
#      port: 8500

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            - Path=/r4j/**
#          filters:
#            - DecryptRequestBody
#            - EncryptResponseBody

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            - Path=/r4j/** # 路径匹配
#            - Before=2023-03-05T11:09:00.9896784+08:00[Asia/Shanghai]

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            - Path=/r4j/**
#            # After断言
#            - After=2019-09-14T11:57:00.9896784+08:00[Asia/Shanghai]

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/r4j/**
#            # Between断言配置
#            - Between=2019-09-14T13:18:53.5890502+08:00[Asia/Shanghai],2019-09-14T13:20:53.5890502+08:00[Asia/Shanghai]

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/r4j/**
#            # Cookie断言
#            - Cookie=cookies_id,abcd.*

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/r4j/**
#            # 请求头断言
#            - Header=id, ^[0-9]*$

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/r4j/**
#            # Host断言
#            - Host=**.host.com:3001,**.myhost.com:3001

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/r4j/**
#            # Method断言
#            - Method=GET

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: user
#          # 转发URI
#          uri: http://localhost:6001
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/user/info/{id},/user/infoes2

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/r4j/**
#            # Query断言，要求存在名为“id”的请求参数，且全为数字组成  ①
#            - Query=id,^[0-9]*$
#            # Query断言，要求存在名为“id”的请求参数  ②
#            # - Query=id


#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/r4j/**
#            # RemoteAddr路由断言工厂
#            - RemoteAddr=192.168.1.0/0, 192.168.1.0/32

#  cloud:
#    gateway:
#      # 开始配置路径
#      routes:
#        # 路径匹配
#        - id: fund
#          # 转发URI
#          uri: http://localhost:7001
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/r4j/**
#            # 权重配置，第一个参数为组名，第二个参数为权重
#            - Weight=fund-group-name,80
#        # 路径匹配
#        - id: fund2
#          # 转发URI
#          uri: http://localhost:7002
#          # 断言配置
#          predicates:
#            # Path断言
#            - Path=/r4j/**
#            # 权重配置，第一个参数为组名，第二个参数为权重
#            - Weight=fund-group-name,20

#  cloud:
#    gateway:
#      routes:
#        # 路由编号
#        - id: user-service
#          # 转发URI
#          uri: http://localhost:6001
#          # 断言配置
#          predicates:
#            # 路径匹配
#            - Path=/user/**
#          # 过滤器工厂
#          filters:
#            # 请求头参数
#            - AddRequestHeader=id, 1

#  cloud:
#    gateway:
#      routes:
#        # 路由编号
#        - id: user-service
#          # 转发URI
#          uri: http://localhost:6001
#          # 断言配置
#          predicates:
#            # 路径匹配
#            - Path=/user/**
#            # 过滤器工厂
#          filters:
#            # 增加一个请求参数
#            - AddRequestParameter=id, 1

#  cloud:
#    gateway:
#      routes:
#        # 路由编号
#        - id: user-service
#          # 转发URI
#          uri: http://localhost:6001
#          # 断言配置
#          predicates:
#            # 路径匹配
#            - Path=/user/**
#          # 过滤器工厂
#          filters:
#            # AddResponseHeader过滤器工厂
#            - AddResponseHeader=token, a123456789

#  cloud:
#    gateway:
#      routes:
#        # 路由编号
#        - id: user-service
#          # 转发URI
#          uri: http://localhost:6001
#          # 断言配置
#          predicates:
#            # 路径匹配
#            - Path=/user/**
#          # 过滤器工厂
#          filters:
#            # 过滤器工厂名称
#            - name: Retry
#              # 配置参数（对应RetryGatewayFilterFactory.RetryConfig）
#              args:
#                # 重试次数，默认为3
#                retries: 2
#                # 对应HTTP请求方法，默认只包含GET
#                methods: GET, POST, PUT
#                # 状态限制
#                statuses: INTERNAL_SERVER_ERROR, BAD_REQUEST
#                # 系列限制
#                series: SERVER_ERROR

#  cloud:
#    gateway:
#      routes:
#        # 路由编号
#        - id: user-service
#          # 转发URI
#          uri: http://localhost:6001
#          # 断言配置
#          predicates:
#            # 路径匹配
#            - Path=/user/**
#          # 过滤器工厂
#          filters:
#            # Hystrix过滤器工厂
#            - name: Hystrix
#              # Hystrix配置参数
#              args:
#                # Hystrix命令名称
#                name: hystrix-cmd
#                # 降级服务请求路径
#                fallbackUri: forward:/gateway/fallback

# resilience4j配置
#resilience4j:
#  # 限速器注册机
#  ratelimiter:
#    limiters:
#      # 名称为user的限速器
#      user:
#        # 时间戳内限制通过的请求数，默认为50
#        limitForPeriod: 3
#        # 配置时间戳（单位毫秒），默认值为500 ns
#        limitRefreshPeriodInMillis: 5000
#        # 超时时间
#        timeoutInMillis: 10

#  cloud:
    gateway:
      routes:
        - id: user-service
          # 客户端负载均衡路由
          uri: lb://gateway-user
          # 匹配路径
          predicates:
            - Path=/user/**
        - id: fund-service
          # 客户端负载均衡路由
          uri: lb://gateway-fund
          # 匹配路径
          predicates:
            - Path=/r4j/**

#management:
#  endpoints:
#    web:
#      # 暴露端点
#      exposure:
#        # 配置暴露的端点
#        include: gateway


