spring:
  datasouce:
    master:
      jdbc-url: jdbc:mysql://192.168.88.111:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.88.112:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.88.113:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations:
    classpath: mapper/*.xml