create table book(
    id int(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    book_name VARCHAR(50) NOT NULL COMMENT '书名',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);