spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: s3cr3t